export const fluidUtilities = {
  'f-text': 'font-size',
  'f-w': 'width',
  'f-w-min': 'min-width',
  'f-w-max': 'max-width',
  'f-h': 'height',
  'f-h-min': 'min-height',
  'f-h-max': 'max-height',
  'f-p': 'padding',
  'f-pt': 'padding-top',
  'f-pb': 'padding-bottom',
  'f-pl': 'padding-left',
  'f-px': ['padding-left', 'padding-right'],
  'f-py': ['padding-top', 'padding-bottom'],
  'f-m': 'margin',
  'f-mt': 'margin-top',
  'f-mb': 'margin-bottom',
  'f-ml': 'margin-left',
  'f-mx': ['margin-left', 'margin-right'],
  'f-my': ['margin-top', 'margin-bottom'],
  'f-gap': 'gap',
  'f-gap-x': 'column-gap',
  'f-gap-y': 'row-gap',
  'f-indent': 'text-indent',
  'f-scroll-m': 'scroll-margin',
  'f-scroll-mt': 'scroll-margin-top',
  'f-scroll-mb': 'scroll-margin-bottom',
  'f-scroll-ml': 'scroll-margin-left',
  'f-scroll-mr': 'scroll-margin-right',
  'f-scroll-mx': ['scroll-margin-left', 'scroll-margin-right'],
  'f-scroll-my': ['scroll-margin-top', 'scroll-margin-bottom'],
  'f-scroll-ms': 'scroll-margin-inline-start',
  'f-scroll-me': 'scroll-margin-inline-end',
  'f-scroll-p': 'scroll-padding',
  'f-scroll-pt': 'scroll-padding-top',
  'f-scroll-pb': 'scroll-padding-bottom',
  'f-scroll-pl': 'scroll-padding-left',
  'f-scroll-pr': 'scroll-padding-right',
  'f-scroll-px': ['scroll-padding-left', 'scroll-padding-right'],
  'f-scroll-py': ['scroll-padding-top', 'scroll-padding-bottom'],
  'f-scroll-ps': 'scroll-padding-inline-start',
  'f-scroll-pe': 'scroll-padding-inline-end',
  'f-leading': 'line-height',
  'f-top': 'top',
  'f-right': 'right',
  'f-bottom': 'bottom',
  'f-left': 'left',
  'f-inset': 'inset',
  'f-inset-x': ['left', 'right'],
  'f-inset-y': ['top', 'bottom'],
}
